version: "3"
services:
  nginx-ssl-sample:
    build: .
    image: nginx-ssl-sample
    container_name: nginx-ssl-sample
    ports:
      - "443:443"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./index.html:/home/www/document-root/index.html